import constants from 'flux-constants'

export default constants([
  'RECEIVE_CATEGORIES',
  'RECEIVE_SUPPLIES',
  'UPDATE_SUPPLY_SUCCESS',
  'UPDATE_ASSET_SUCCESS',
  'RECEIVE_ASSETS',
  'RECEIVE_ASSETS_CATEGORIES',
  'ADD_CATEGORY',
  'ADD_SUPPLY',
  'ADD_ASSET',
  'ADD_CATEGORY_ASSETS',
  'REQUEST_LOCAL_LOGIN',
  'SUCCESS_LOCAL_LOGIN',
  'FAILURE_LOCAL_LOGIN',
  'REQUEST_LOCAL_LOGOUT',
  'SUCCESS_LOCAL_LOGOUT',
  'FAILURE_LOCAL_LOGOUT',
  'RECEIVE_REPORTS_TOTAL_VALUE',
  'RECEIVE_REPORTS_INVENTARY_AMOUNT',
  'RECEIVE_REPORTS_SUPPLY_CONSUPTION',
  'RECEIVE_REPORTS_ASSETS_STATE',
  'RECEIVE_REPORTS_LOG',
  'RECEIVE_REPORTS_SUPPLIES_PER_LAB',
  'RECEIVE_SUPPLY_AMOUNT',
  'UPDATE_SUPPLY_AMOUNT_SUCCESS'
])
